name: create-release-artifact

on:
  release:
    types: [published]

jobs:
  create-release-artifact:
    name: Creating release artifact
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cached dependencies
        uses: actions/cache@v2
        id: cached-dependencies
        with:
          path: ./vendor
          # the key will change if composer.lock changes
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/composer.lock') }}

      - name: install dependencies
        uses: php-actions/composer@v6
        with:
          command: run build:prod

      - name: build artifact
        run: composer run package && mv ./tmp/tawk_to.zip tawk_to.zip

      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./tawk_to.zip
          asset_name: tawk_to.zip
          asset_content_type: application/zip
